# conda env create -f environment.yml
# conda env update -f environment.yml

name: med_sdoh
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python>=3.12
  - pandas
  - matplotlib
  - numpy
  - ipykernel
  - requests
  - pip:
      - beautifulsoup4
      - python-dotenv
      - pyodbc
      - -e .
